title: "Jianbo's Blog"
author: "Jianbo Dai"
description: "Keep moving. Don't settle."
permalink: /:title/
lang: "en"
date_format: "%B %d, %Y"

# Layout

sidebar: true                # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: true            # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: false               # minima-inspired style without box-shadows

# Menu

navigation:
  - {file: "index.html", icon: book-open}
#  - {file: "homepage.md", icon: home}
  - {file: "README.md", icon: address-card}

external:                    # see http://fontawesome.com/icons
  - {title: Zhihu, icon: zhihu, url: "https://www.zhihu.com/people/wang-ming-wei-70-76"}
  - {title: Github, icon: github, url: "https://github.com/1e0ndavid"}
  - {title: Mail, icon: envelope, url: "mailto:jianbodai819@gmai.com"}
#   - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus: ""                # see https://disqus.com/
#  isso: ""                  # see https://posativ.org/isso/

plugins:
 - jekyll-feed

mathjax: true
